version: '2.0'
services:
  chatgpt-on-wechat:
    image: wechatgpt:2024
#    container_name: wechatgpt
    security_opt:
      - seccomp:unconfined
    environment:
      MODEL: 'glm-4'   # 聊天模型
      ZHIPU_AI_API_KEY: ''  # zhipuai api_key
      TEXT_TO_IMAGE: "cogview-3"  # 图片模型 zhipuai
      CHANNEL_TYPE: 'wx'  # 通道类型 这里是微信
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["robot", "@robot"]'  # 单聊触发前缀
      SINGLE_CHAT_REPLY_PREFIX: '"[robot] "'  # 单聊回复前缀
      GROUP_CHAT_PREFIX: '["@robot"]'  # 群聊触发前缀
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'  # 群聊哪些适用自动回复, 可以全部群聊适用ALL_GROUP，或者填写具体适用的群聊名称
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'  # 绘画触发前缀，
      NICK_NAME_BLACK_LIST: '[""]'  # 不回复的用户昵称
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是一个大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      ZHIPU_AI_APP_ID: ''
